# 포트
server:
  port: 8080

# 오라클
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(gTuyEd7OSGBITu/JnnAyMl/OGKd8v+IRL7pO7ZHEPcfxLOs4BYr5hejFh///dTkaFSpgA+VwvtfjYtL/pS5UJC2vDuvQREZ/851o317RXbVwvRaGt39KRXnosD6WN0WFkBQuIbYP8j8=)
    username: ENC(zuoJ802bn4Kgil7G3axzSA==)
    password: ENC(UQ3VKKrjaFsLg02mQnIw/OS7WVSjWFzX)

# 마이바티스
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# 암호화 설정
jasypt:
  encryptor:
    bean: jasyptStringEncryptor